# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 21:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budgetr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 30, 21, 31, 17, 475887, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
