# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetr', '0002_flow_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
