# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-30 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetr', '0003_auto_20170430_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='memo',
            field=models.FloatField(default=0),
        ),
    ]
