# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetr', '0005_auto_20170430_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='goal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
